version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db/todo/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always